use std::array;

use tracy_macros::{Random, fields, ops};
use tracy_traits::{Num, Random};

use crate::arr_store::{self, ArrStore};

#[derive(Clone, Copy, Debug, Default, Random)]
#[fields(r, g, b)]
#[ops(
    add,
    sub,
    mul,
    mul(lhs = T, rhs = T),
    div(rhs = T)
)]
pub struct ColorRGB<T: Num> {
    pub arr: ArrStore<T, 3>,
}

// TODO: This could be a trait generated by a macro.
impl ColorRGB<f64> {
    pub fn to_u8(&self) -> ColorRGB<u8> {
        ColorRGB {
            arr: ArrStore(array::from_fn(|i| {
                (self.arr[i].clamp(0.0, 1.0) * 255.0) as u8
            })),
        }
    }

    pub fn to_gamma(&self) -> Self {
        Self {
            arr: ArrStore(array::from_fn(|i| {
                f64::max(self.arr[i], 0.0).sqrt()
            })),
        }
    }
}

#[derive(Clone, Copy, Debug, Default, Random)]
#[fields(r, g, b, a)]
#[ops(
    add,
    sub,
    mul,
    mul(lhs = T, rhs = T),
    div(rhs = T)
)]
pub struct ColorRGBA<T: Num> {
    pub arr: ArrStore<T, 4>,
}

impl ColorRGBA<f64> {
    pub fn to_u8(&self) -> ColorRGBA<u8> {
        ColorRGBA {
            arr: ArrStore(array::from_fn(|i| {
                (self.arr[i].clamp(0.0, 1.0) * 255.0) as u8
            })),
        }
    }
}
